-- =========================================
-- OPD Medication Signature v2.0 - Production Database Setup
-- Safe to run more than once in Supabase SQL Editor.
-- =========================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Core tables
CREATE TABLE IF NOT EXISTS public.transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    hn TEXT NOT NULL,
    staff_id TEXT NOT NULL,
    staff_name TEXT,
    receiver_type TEXT NOT NULL,
    signature_url TEXT,
    service_date DATE NOT NULL,
    device_id TEXT,
    status TEXT DEFAULT 'COMPLETED',
    drive_archive_url TEXT,
    is_duplicate_confirmed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.staff_users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    staff_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    pin TEXT,
    pin_hash TEXT,
    role TEXT DEFAULT 'STAFF',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.staff_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    staff_user_id UUID NOT NULL REFERENCES public.staff_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.transactions ADD COLUMN IF NOT EXISTS is_duplicate_confirmed BOOLEAN DEFAULT FALSE;
ALTER TABLE public.staff_users ADD COLUMN IF NOT EXISTS pin_hash TEXT;
ALTER TABLE public.staff_users ALTER COLUMN pin DROP NOT NULL;

-- Seed/update the first administrator. Change this PIN after first login.
INSERT INTO public.staff_users (staff_id, name, pin, pin_hash, role)
VALUES ('admin', 'System Admin', NULL, crypt('123456', gen_salt('bf')), 'ADMIN')
ON CONFLICT (staff_id) DO UPDATE
SET name = EXCLUDED.name,
    pin = NULL,
    pin_hash = EXCLUDED.pin_hash,
    role = 'ADMIN';

-- Migrate any old plaintext PINs into hashes, then clear the plaintext.
UPDATE public.staff_users
SET pin_hash = crypt(pin, gen_salt('bf')),
    pin = NULL
WHERE pin_hash IS NULL
  AND pin IS NOT NULL
  AND pin <> '';

-- 2. Storage bucket for signature images.
INSERT INTO storage.buckets (id, name, public)
VALUES ('signatures', 'signatures', true)
ON CONFLICT (id) DO UPDATE
SET public = true;

-- 3. Lock down direct table access from browser roles.
REVOKE ALL ON public.staff_users FROM anon, authenticated;
REVOKE ALL ON public.staff_sessions FROM anon, authenticated;
REVOKE ALL ON public.transactions FROM anon, authenticated;
GRANT USAGE ON SCHEMA public TO anon, authenticated;

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No direct browser access to staff_users" ON public.staff_users;
CREATE POLICY "No direct browser access to staff_users"
ON public.staff_users FOR ALL
TO anon, authenticated
USING (false)
WITH CHECK (false);

DROP POLICY IF EXISTS "No direct browser access to staff_sessions" ON public.staff_sessions;
CREATE POLICY "No direct browser access to staff_sessions"
ON public.staff_sessions FOR ALL
TO anon, authenticated
USING (false)
WITH CHECK (false);

DROP POLICY IF EXISTS "No direct browser access to transactions" ON public.transactions;
CREATE POLICY "No direct browser access to transactions"
ON public.transactions FOR ALL
TO anon, authenticated
USING (false)
WITH CHECK (false);

-- Public read/write for signature objects. Filenames generated by the app no longer contain HN.
DROP POLICY IF EXISTS "Public signatures access" ON storage.objects;
DROP POLICY IF EXISTS "Public signatures select" ON storage.objects;
DROP POLICY IF EXISTS "Public signatures insert" ON storage.objects;

CREATE POLICY "Public signatures select"
ON storage.objects FOR SELECT
TO anon, authenticated
USING (bucket_id = 'signatures');

CREATE POLICY "Public signatures insert"
ON storage.objects FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'signatures');

-- 4. RPC helpers and API functions.
CREATE OR REPLACE FUNCTION public.hash_session_token(p_token TEXT)
RETURNS TEXT
LANGUAGE SQL
SECURITY DEFINER
IMMUTABLE
SET search_path = public, extensions
AS $$
    SELECT encode(digest(p_token, 'sha256'), 'hex');
$$;

CREATE OR REPLACE FUNCTION public.require_staff_session(p_session_token TEXT)
RETURNS TABLE (staff_user_id UUID, staff_id TEXT, staff_name TEXT, role TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
    DELETE FROM public.staff_sessions WHERE expires_at < NOW();

    RETURN QUERY
    SELECT su.id, su.staff_id, su.name, su.role
    FROM public.staff_sessions ss
    JOIN public.staff_users su ON su.id = ss.staff_user_id
    WHERE ss.token_hash = public.hash_session_token(p_session_token)
      AND ss.expires_at > NOW()
    LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Session expired or invalid';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.login_staff(p_staff_id TEXT, p_pin TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_staff public.staff_users%ROWTYPE;
    v_token TEXT;
BEGIN
    SELECT * INTO v_staff
    FROM public.staff_users
    WHERE staff_id = trim(p_staff_id)
    LIMIT 1;

    IF v_staff.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'message', 'รหัสเจ้าหน้าที่หรือ PIN ไม่ถูกต้อง');
    END IF;

    IF v_staff.pin_hash IS NULL AND v_staff.pin IS NOT NULL AND v_staff.pin = trim(p_pin) THEN
        UPDATE public.staff_users
        SET pin_hash = crypt(trim(p_pin), gen_salt('bf')),
            pin = NULL
        WHERE id = v_staff.id
        RETURNING * INTO v_staff;
    END IF;

    IF v_staff.pin_hash IS NULL OR crypt(trim(p_pin), v_staff.pin_hash) <> v_staff.pin_hash THEN
        RETURN jsonb_build_object('ok', false, 'message', 'รหัสเจ้าหน้าที่หรือ PIN ไม่ถูกต้อง');
    END IF;

    v_token := replace(gen_random_uuid()::TEXT, '-', '') || replace(gen_random_uuid()::TEXT, '-', '');

    INSERT INTO public.staff_sessions (staff_user_id, token_hash, expires_at)
    VALUES (v_staff.id, public.hash_session_token(v_token), NOW() + INTERVAL '12 hours');

    RETURN jsonb_build_object(
        'ok', true,
        'data', jsonb_build_object(
            'sessionToken', v_token,
            'staffId', v_staff.staff_id,
            'staffName', v_staff.name,
            'role', v_staff.role
        )
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.check_duplicate(p_session_token TEXT, p_hn TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_session RECORD;
    v_tx RECORD;
BEGIN
    SELECT * INTO v_session FROM public.require_staff_session(p_session_token);

    IF p_hn !~ '^07-[0-9]{2}-[0-9]{6}$' THEN
        RETURN jsonb_build_object('ok', false, 'message', 'รูปแบบ HN ไม่ถูกต้อง (ต้องเป็น 07-XX-XXXXXX)');
    END IF;

    SELECT id, created_at, staff_name INTO v_tx
    FROM public.transactions
    WHERE hn = p_hn
      AND created_at >= NOW() - INTERVAL '24 hours'
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_tx.id IS NOT NULL THEN
        RETURN jsonb_build_object(
            'ok', true,
            'code', 'DUPLICATE_FOUND',
            'message', 'พบรายการรับยาซ้ำ',
            'data', jsonb_build_object(
                'recordId', v_tx.id,
                'submittedAt', v_tx.created_at,
                'staffName', v_tx.staff_name
            )
        );
    END IF;

    RETURN jsonb_build_object('ok', true, 'code', 'SUCCESS');
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_transaction(
    p_session_token TEXT,
    p_hn TEXT,
    p_receiver_type TEXT,
    p_signature_url TEXT,
    p_device_id TEXT DEFAULT 'v2-web',
    p_is_duplicate_confirmed BOOLEAN DEFAULT FALSE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_session RECORD;
    v_record public.transactions%ROWTYPE;
    v_service_date DATE := CURRENT_DATE;
BEGIN
    SELECT * INTO v_session FROM public.require_staff_session(p_session_token);

    IF p_hn !~ '^07-[0-9]{2}-[0-9]{6}$' THEN
        RETURN jsonb_build_object('ok', false, 'message', 'รูปแบบ HN ไม่ถูกต้อง (ต้องเป็น 07-XX-XXXXXX)');
    END IF;

    IF p_receiver_type NOT IN ('PATIENT', 'RELATIVE') THEN
        RETURN jsonb_build_object('ok', false, 'message', 'ประเภทผู้รับยาไม่ถูกต้อง');
    END IF;

    INSERT INTO public.transactions (
        hn, staff_id, staff_name, receiver_type, signature_url,
        service_date, device_id, is_duplicate_confirmed
    )
    VALUES (
        p_hn, v_session.staff_id, v_session.staff_name, p_receiver_type, p_signature_url,
        v_service_date, COALESCE(p_device_id, 'v2-web'), COALESCE(p_is_duplicate_confirmed, FALSE)
    )
    RETURNING * INTO v_record;

    RETURN jsonb_build_object(
        'ok', true,
        'message', 'บันทึกข้อมูลเรียบร้อยแล้ว',
        'data', jsonb_build_object(
            'recordId', v_record.id,
            'serverTime', v_record.created_at,
            'serviceDate', v_record.service_date,
            'staffId', v_record.staff_id,
            'staffName', v_record.staff_name
        )
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.list_transactions(
    p_session_token TEXT,
    p_hn TEXT DEFAULT NULL,
    p_service_date DATE DEFAULT NULL
)
RETURNS TABLE (
    id UUID,
    created_at TIMESTAMPTZ,
    hn TEXT,
    staff_id TEXT,
    staff_name TEXT,
    receiver_type TEXT,
    signature_url TEXT,
    drive_archive_url TEXT,
    service_date DATE
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_session RECORD;
BEGIN
    SELECT * INTO v_session FROM public.require_staff_session(p_session_token);

    RETURN QUERY
    SELECT t.id, t.created_at, t.hn, t.staff_id, t.staff_name, t.receiver_type,
           t.signature_url, t.drive_archive_url, t.service_date
    FROM public.transactions t
    WHERE (p_hn IS NULL OR t.hn = p_hn)
      AND (p_service_date IS NULL OR t.service_date = p_service_date)
    ORDER BY t.created_at DESC
    LIMIT 100;
END;
$$;

CREATE OR REPLACE FUNCTION public.list_staff(p_session_token TEXT)
RETURNS TABLE (
    id UUID,
    staff_id TEXT,
    name TEXT,
    role TEXT,
    created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_session RECORD;
BEGIN
    SELECT * INTO v_session FROM public.require_staff_session(p_session_token);

    IF v_session.role <> 'ADMIN' THEN
        RAISE EXCEPTION 'Admin role required';
    END IF;

    RETURN QUERY
    SELECT su.id, su.staff_id, su.name, su.role, su.created_at
    FROM public.staff_users su
    ORDER BY su.created_at ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public.add_staff(
    p_session_token TEXT,
    p_staff_id TEXT,
    p_name TEXT,
    p_pin TEXT,
    p_role TEXT DEFAULT 'STAFF'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_session RECORD;
    v_role TEXT := CASE WHEN upper(coalesce(p_role, 'STAFF')) = 'ADMIN' THEN 'ADMIN' ELSE 'STAFF' END;
BEGIN
    SELECT * INTO v_session FROM public.require_staff_session(p_session_token);

    IF v_session.role <> 'ADMIN' THEN
        RAISE EXCEPTION 'Admin role required';
    END IF;

    IF trim(coalesce(p_staff_id, '')) = '' OR trim(coalesce(p_name, '')) = '' THEN
        RETURN jsonb_build_object('ok', false, 'message', 'กรุณากรอกรหัสและชื่อพนักงาน');
    END IF;

    IF trim(coalesce(p_pin, '')) !~ '^[0-9]{4,6}$' THEN
        RETURN jsonb_build_object('ok', false, 'message', 'PIN ต้องเป็นตัวเลข 4-6 หลัก');
    END IF;

    INSERT INTO public.staff_users (staff_id, name, pin, pin_hash, role)
    VALUES (trim(p_staff_id), trim(p_name), NULL, crypt(trim(p_pin), gen_salt('bf')), v_role);

    RETURN jsonb_build_object('ok', true);
EXCEPTION
    WHEN unique_violation THEN
        RETURN jsonb_build_object('ok', false, 'message', 'รหัสพนักงานนี้มีอยู่แล้ว');
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_staff(p_session_token TEXT, p_staff_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_session RECORD;
    v_target public.staff_users%ROWTYPE;
    v_admin_count INTEGER;
BEGIN
    SELECT * INTO v_session FROM public.require_staff_session(p_session_token);

    IF v_session.role <> 'ADMIN' THEN
        RAISE EXCEPTION 'Admin role required';
    END IF;

    SELECT * INTO v_target FROM public.staff_users WHERE id = p_staff_user_id;
    IF v_target.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'message', 'ไม่พบพนักงาน');
    END IF;

    IF v_target.id = v_session.staff_user_id THEN
        RETURN jsonb_build_object('ok', false, 'message', 'ไม่สามารถลบบัญชีที่กำลังใช้งานอยู่');
    END IF;

    IF v_target.role = 'ADMIN' THEN
        SELECT count(*) INTO v_admin_count FROM public.staff_users WHERE role = 'ADMIN';
        IF v_admin_count <= 1 THEN
            RETURN jsonb_build_object('ok', false, 'message', 'ต้องมี ADMIN อย่างน้อย 1 คน');
        END IF;
    END IF;

    DELETE FROM public.staff_users WHERE id = p_staff_user_id;
    RETURN jsonb_build_object('ok', true);
END;
$$;

REVOKE ALL ON FUNCTION public.hash_session_token(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.require_staff_session(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.login_staff(TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_duplicate(TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_transaction(TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.list_transactions(TEXT, TEXT, DATE) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.list_staff(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.add_staff(TEXT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_staff(TEXT, UUID) TO anon, authenticated;
